version : '3.8'

services:
   db:
      image: postgres:latest
      environment:
        POSTGRES_USER: filsa_dev
        POSTGRES_PASSWORD: Filsa.2024
        POSTGRES_DB: filsadb_dev
      ports:
        - "5432:5432"
      volumes:
        - db_data:/var/lib/postgresql/data/
    

volumes:
   db_data:
# version: "3.7"

# services:
#     webapp:
#         build: .
#         container_name: filsa_app
       
#         # env_file: .env
#         ports:
#             - 8000:8000

#     postgres:
#         image: postgres:latest
#         container_name: filsa_postgres
#         environment:
#             POSTGRES_USER: filsa
#             POSTGRES_PASSWORD: Filsa.2024
#             POSTGRES_DB: filsadb
#         ports:
#             - 5432:5432
#         volumes:
#             - postgres_data:/var/lib/postgresql/data
#         restart: always
# volumes:
#     postgres_data:
#         driver: local